[package]
name = "image-sr"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["wgpu"] }
clap = { version = "4.5.21", features = ["derive"] }
image = "0.25.5"
walkdir = "2.5.0"
